### ISSUE TITLE
Cannot Edit Any Unit Attributes Unless it is set to player

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#1]
>#### Instructions
Mods: CBA, ACE3, MissionFramework, ACRE2, Mission Framework ACRE2 

Place a unit down, make him not player and close the attributes dialog
Place another unit down, make him player

You can no longer edit the unit who is not player.
If you make both units not player, you will not be able to edit either of them.

You will no longer be able to edit the unit that is set to not player. Further, 3Den will be frozen due to a dialogue not being displayed properly. You can resume control by pressing ESC.

![20190806014831_1](https://user-images.githubusercontent.com/16574249/62514196-6c616d80-b7ec-11e9-9836-08a115d2e8e6.jpg)

**Comment by PiZZAD0X** [comment]
Attribute menu could not be created due to an issue of nested controls in attributes, new method of detecting player/ai only categories seems to work. Updated workshop with https://github.com/PiZZAD0X/MMFW/commit/25fc408c79589bc454461469b1b5bf7c6eabd25a
