### ISSUE TITLE
End Conditions not working

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#10]
End conditions do not fire when set to check for dead entities, sufficient blufor dead, I am unsure about timers or anything else at this point, bu
[rpt (2).txt](https://github.com/PiZZAD0X/MMFW/files/3543792/rpt.2.txt)

t right now these are the ones that I'm certain of. 

Test mission and RPT attached.

[testEnd.VR.zip](https://github.com/PiZZAD0X/MMFW/files/3543791/testEnd.VR.zip)

**Comment by PiZZAD0X** [comment]
Try with latest build, should print detailed info on end conditions

**Comment by JudahHarvey** [comment]
End conditions still not firing, Tested
Blufor Casualties (Any condition)
Dead hostage (Any condition)
Objectives Accomplished and Extract

[SecureTheBag.Stratis.zip](https://github.com/PiZZAD0X/MMFW/files/3562966/SecureTheBag.Stratis.zip)

[arma3_x64_2019-08-31_19-46-45 - Copy.rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3562969/arma3_x64_2019-08-31_19-46-45.-.Copy.rpt.txt)

**Comment by JudahHarvey** [comment]
Blufor Casualties currently does not count even when all blufor players are dead

**Comment by JudahHarvey** [comment]
Disregard, this issue is solved
