### ISSUE TITLE
Error when selecting blufor respawn settings, cannot set respawn system settings for any respawn type

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#11]
Mods Related
CBA, ACE3, ACRE2, MMFW

Use previous test mission to recreate this bug. RPT attached
[rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3547271/rpt.txt)

Screenshot attached. Error repeats for Opfor, Indfor, and Civilian respawn settings. 

![107410_20190827123858_1](https://user-images.githubusercontent.com/16574249/63791748-2323ab80-c8ca-11e9-93e9-30d6600187a6.png)

**Comment by PiZZAD0X** [comment]
44931f0801b948e7f804fdbbbcf276c818b69e6e
