### ISSUE TITLE
Capture Zone Variables not being set or changed on capture

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#12]
As described. Zone1 does not appear as a variable of any defintion and does not receive a defintion upon capture. Relevant RPT and mission files attached

[testme.VR.zip](https://github.com/PiZZAD0X/MMFW/files/3562767/testme.VR.zip)
[arma3_x64_2019-08-31_14-12-53.rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3562768/arma3_x64_2019-08-31_14-12-53.rpt.txt)

**Comment by PiZZAD0X** [comment]
8edfffda98b355b97b22c756329b1b6ea0dd5373

**Comment by JudahHarvey** [comment]
Strange looping error detected for capture zones. Previous uploaded testing content should be sufficinet to perform test, RPT attached.

[arma3_x64_2019-08-31_19-46-45 - Copy.rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3562974/arma3_x64_2019-08-31_19-46-45.-.Copy.rpt.txt)

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/MMFW/commit/2827dfa55ca1a5f6fb4d0e9c59703a51b1b8bcd7

**Comment by JudahHarvey** [comment]
Confirmed Fixed
