### ISSUE TITLE
Easy way to extend mission timer mid mission

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#2]
Sometimes, administrators might want to end a mission at a later time what what is set by the mission author. It would be nice if we could have this feature embedded into the framework as maybe a button that's clicked in the briefing menu, or at least a command that could be executed by the admin.

**Comment by PiZZAD0X** [comment]
A set of chat commands to check and extend mission time sound like a great idea

**Comment by PiZZAD0X** [comment]
`timelimit extend 5` will extend the timelimit by five minutes, show the new timelimit and time left in the mission
`timelimit check` will display the timelimit and time left in the mission

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/MMFW/blob/e17dfd99eb9307fb9637434288a454f9519e88e0/addons/core/functions/fnc_chatCommands.sqf#L12
