### ISSUE TITLE
Pre Init, Post Init, and Description.ext extension fields

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#4]
It would be very useful to be able to execute arbitrary pre and post init functions or scripts from within the editor, without having to resort to an additional script file. A field within the framework, simply titled "Post Init" or "pre Init" with a checkbox to enable or disable, as well as a way to extend description.ext with a similar checkbox would go a very long way to eliminating all files outside of mission.sqm

**Comment by PiZZAD0X** [comment]
Pre/Post Init is very possible from within the editor, however editing description.ext requires a make file extension that introduces a whole load of security issues and file permission complications.

**Comment by PiZZAD0X** [comment]
![6-NWsvQnScWtwEmEepcPtA](https://user-images.githubusercontent.com/11909749/63448601-1ba86200-c3f3-11e9-9b5c-35725c9a35ad.png)
