### ISSUE TITLE
Briefing Categories Reversed for NATO Blufor

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#7]
See screenshot. Categories start at V and go down to I. Not all categories were filled
![20190817152622_1](https://user-images.githubusercontent.com/16574249/63216448-7bf18800-c103-11e9-9251-6f946df092ff.jpg)

**Comment by PiZZAD0X** [comment]
![h8V4GLXKTTyM7NS59r0hcA](https://user-images.githubusercontent.com/11909749/63216595-70df2d80-c0ec-11e9-986c-9caa0e34dd48.png)

Fixed in next push

**Comment by PiZZAD0X** [comment]
https://github.com/PiZZAD0X/MMFW/commit/2674e9e4c42bcc2f42cd231dfe085caff66fe8ae
