### ISSUE TITLE
AO Module needs a example.

### ISSUE THREAD

**Issue by Jason-Terry** [PiZZAD0X/MMFW#8]
Can not get the AO module to kill a player when they exit the AO.

**Comment by TrainDoctor** [comment]
This is not a bug report.

Here's what an actual bug report looks like.

> 
>#### Instructions
>
>With the exception of the instructions and naming convention, headers should be kept with the description changed to their respective function. Put "nil" if not applicable.
>
>#### Naming Convention
>
>Bug reports should be named "Bug Report: Short description of Problem"  
>eg. "Bug Report: Player vehicles not activating AI spawn zone"
> 
> #### Description of issue
> 
> Add a clear and concise description of the error. This makes it easier for us to fix the issue.
> 
> #### Logs
> 
> Include a link to the pastebin/gist of your RPT log(s).
> 
> #### Mission File(s)
> 
> Please include a link to a .zip of your root mission folder here.
> 
> #### Steps to reproduce
> 
> Add the steps needed to reproduce the issue. For example:
> 
> 1.  Go on '...'
> 2.  Click on '...'
> 3.  Scroll down to '...'
> 4.  See error
> 
> #### Expected behaviour
> 
> A clear and concise description of what you expected to happen.
> 
> #### Video and Screenshots
> 
> Post a screenshot of the bug. This makes it easier to identify and fix the issue.
> 
> #### Additional context
> 
> Add any other context about the problem here you feel may be relevant.

**Comment by PiZZAD0X** [comment]
5e3a313d266bea05cea103e1c5e29bb95aefe4f1
