### ISSUE TITLE
Hostage Module not Functioning

### ISSUE THREAD

**Issue by JudahHarvey** [PiZZAD0X/MMFW#9]
Mods: CBAA3, ACE3, ACRE2, MMFW
Map: Virtual Reality
Steps: 
Place blufor player unit, static house, hostage module ontop of static house,
place civilian unit, set hostage attributes as default, link to module
create end condition in relation to hostage.
Enable Framework checkbox.

Result:
Hostage is not tied up, mission cannot be completed

[rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3543768/rpt.txt)
[testhostage.VR.zip](https://github.com/PiZZAD0X/MMFW/files/3543769/testhostage.VR.zip)

**Comment by PiZZAD0X** [comment]
c15cd2af398b82e12ba820d8e627c2f7e637fc9c

**Comment by JudahHarvey** [comment]
Hostage module functions, but does not actually change variables 
MMFW_Hostagename_isUntied

is never set properly
[arma3_x64_2019-08-31_19-46-45 - Copy.rpt.txt](https://github.com/PiZZAD0X/MMFW/files/3562971/arma3_x64_2019-08-31_19-46-45.-.Copy.rpt.txt)
[SecureTheBag.Stratis.zip](https://github.com/PiZZAD0X/MMFW/files/3562972/SecureTheBag.Stratis.zip)

**Comment by PiZZAD0X** [comment]
unit getvariable ["mmfw_hostage_isUntied",false]
unit getvariable ["mmfw_hostage_isRescued",false]

**Comment by JudahHarvey** [comment]
Fixed
